// Generated by Church Bulletin Builder. Edit document.json in the app.
#set page(width: 7in, height: 8.5in, margin: 0pt, fill: rgb("#fffaf1"))
#set text(font: "Calibri", size: 11pt)
#set par(first-line-indent: 0pt, spacing: 0.35em)

#place(dx: 28.5pt, dy: 21pt)[
  #box(width: 447pt, height: 31.5pt, inset: 6pt)[
    #set align(left)
    #text(font: "Eras Demi ITC", size: 13.5pt, fill: rgb("#251d18"), weight: "bold")[
      Second Sunday After Pentecost    June 7, 2026
    ]
  ]
]

#place(dx: 144pt, dy: 127.5pt)[
  #box(width: 216pt, height: 112.5pt, inset: 6pt)[
    #image("../../../assets/sermon_series/say_it_out_loud/logo.png", width: 100%, height: 100%, fit: "contain")
  ]
]

#place(dx: 64.5pt, dy: 296.25pt)[
  #box(width: 375pt, height: 51pt, inset: 6pt)[
    #set align(center)
    #text(font: "Eras Demi ITC", size: 18pt, fill: rgb("#251d18"), weight: "bold")[
      GOD LOVES SINNERS\*
    ]
  ]
]

#place(dx: 305.25pt, dy: 511.5pt)[
  #box(width: 162pt, height: 61.5pt, inset: 6pt)[
    #image("../../../assets/church/logo.png", width: 100%, height: 100%, fit: "contain")
  ]
]

#place(dx: 48pt, dy: 66pt)[
  #box(width: 195pt, height: 58.5pt, inset: 6pt, fill: rgb("#ffffff"), stroke: 0.75pt + rgb("#d8cdbd"))[
    #set align(left)
    #text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[
      Add bulletin sections by dragging elements from the palette. Use the inspector for exact placement and styling.
    ]
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 225pt, height: 90pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #align(center + horizon)[
      #text(size: 14pt, weight: "bold")[Music / Lead Sheet]
      #linebreak()
      #text(size: 9pt, style: "italic")[Import support TBD]
    ]
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #stack(dir: ttb, spacing: 6pt,
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[First item]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Second item]]
    )
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #grid(
      columns: (1fr, 1fr),
      rows: 2,
      gutter: 4.5pt,
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 1]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 2]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 3]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 4]],
    )
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #stack(dir: ttb, spacing: 6pt,
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[First item]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Second item]]
    )
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 225pt, height: 90pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #align(center + horizon)[
      #text(size: 14pt, weight: "bold")[Music / Lead Sheet]
      #linebreak()
      #text(size: 9pt, style: "italic")[Import support TBD]
    ]
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #stack(dir: ttb, spacing: 6pt,
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[First item]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Second item]]
    )
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, stroke: 0.75pt + rgb("#d8cdbd"))[
    #grid(
      columns: (1fr, 1fr),
      rows: 2,
      gutter: 4.5pt,
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 1]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 2]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 3]],
      [#text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[Cell 4]],
    )
  ]
]

#place(dx: 60pt, dy: 60pt)[
  #box(width: 135pt, height: 82.5pt, inset: 6pt)[
    #image("../../../assets/church/ChurchCross.png", width: 100%, height: 100%, fit: "contain")
  ]
]

#place(dx: 67.5pt, dy: 225.75pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, fill: rgb("#ffffff"), stroke: 0.75pt + rgb("#d8cdbd"))[
    #set align(left)
    #text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[
      Text element
    ]
  ]
]
