// Generated by Church Bulletin Builder. Edit document.json in the app.
#set page(width: 7in, height: 8.5in, margin: 0pt)
#set text(font: "Calibri", size: 11pt)
#set par(first-line-indent: 0pt, spacing: 0.35em)

#rect(width: 100%, height: 100%, fill: rgb("#fffaf1"))

#place(dx: 28.5pt, dy: 21pt)[
  #box(width: 447pt, height: 31.5pt, inset: 6pt)[
    #set align(left)
    #text(font: "Eras Demi ITC", size: 13.5pt, fill: rgb("#251d18"), weight: "bold")[
      Second Sunday After Pentecost    June 7, 2026
    ]
  ]
]

#place(dx: 141.75pt, dy: 152.25pt)[
  #box(width: 216pt, height: 112.5pt, inset: 6pt, stroke: 3.75pt + rgb("#613583"))[
    #image("../../../assets/sermon_series/say_it_out_loud/logo.png", width: 100%, height: 100%, fit: "contain")
  ]
]

#place(dx: 64.5pt, dy: 296.25pt)[
  #box(width: 375pt, height: 51pt, inset: 6pt)[
    #set align(center)
    #text(font: "Eras Demi ITC", size: 18pt, fill: rgb("#251d18"), weight: "bold")[
      GOD LOVES SINNERS asdfjkdsaf askljfaklsdjf
    ]
  ]
]

#place(dx: 305.25pt, dy: 511.5pt)[
  #box(width: 162pt, height: 61.5pt, inset: 6pt)[
    #image("../../../assets/church/logo.png", width: 100%, height: 100%, fit: "contain")
  ]
]

#place(dx: 31.5pt, dy: 64.5pt)[
  #box(width: 195pt, height: 58.5pt, inset: 6pt, fill: rgb("#ffffff"), stroke: 0.75pt + rgb("#d8cdbd"))[
    #set align(left)
    #text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[
      Add bulletin sections by dragging elements from the palette. Use the inspector for exact placement and styling.
    ]
  ]
]

#place(dx: 22.5pt, dy: 240.75pt)[
  #box(width: 165pt, height: 67.5pt, inset: 6pt, fill: rgb("#ffffff"), stroke: 0.75pt + rgb("#d8cdbd"))[
    #set align(left)
    #text(font: "Calibri", size: 8.25pt, fill: rgb("#251d18"))[
      Text element
    ]
  ]
]
