import { normalizeAssetPath } from "./storage.js";

const ptPerPx = 0.75;

export function renderTypst(project, { assetPrefix = "../../../assets" } = {}) {
  const page = project.page || {};
  const elements = Array.isArray(project.elements) ? project.elements : [];
  return `// Generated by Church Bulletin Builder. Edit document.json in the app.
#set page(width: ${page.typstWidth || "7in"}, height: ${page.typstHeight || "8.5in"}, margin: 0pt, fill: ${color(page.background || "#ffffff")})
#set text(font: "Calibri", size: 11pt)
#set par(first-line-indent: 0pt, spacing: 0.35em)

${elements.map((element) => renderElement(element, { assetPrefix, page })).join("\n\n")}
`;
}

function renderElement(element, context) {
  if (element.type === "pageBreak") return "#pagebreak()";
  if (element.type === "canvas") return renderCanvasBlock(element, context);
  const body = renderElementBody(element, context);
  const margin = numericLength(element.margin) > 0 ? `#v(${typstLength(element.margin)})\n` : "";
  return `${margin}#block(${boxArgs(element)})[
${indent(body, 4)}
]${margin ? `\n${margin.trimEnd()}` : ""}`;
}

function renderElementBody(element, context) {
  if (element.type === "image") return renderImage(element, context);
  if (element.type === "grid") return renderGrid(element, context);
  if (element.type === "stack") return renderStack(element, context);
  if (element.type === "music") return renderMusic(element);
  if (element.type === "date") return renderText(element, renderDateText(element));
  return renderText(element, element.data?.text || "");
}

function renderCanvasBlock(element, context) {
  const margin = numericLength(element.margin) > 0 ? `#v(${typstLength(element.margin)})\n` : "";
  const children = renderCanvasChildren(element, context);
  return `${margin}#block(${canvasBoxArgs(element, context)})[
${indent(children || "", 2)}
]${margin ? `\n${margin.trimEnd()}` : ""}`;
}

function renderCanvasBox(element, context, forcedSize) {
  return `#box(${canvasBoxArgs(element, context, forcedSize)})[
${indent(renderCanvasChildren(element, context), 2)}
]`;
}

function renderCanvasChildren(element, context) {
  return (element.children || []).map((child) => renderCanvasChild(child, element, context)).join("\n");
}

function renderCanvasChild(child, parentCanvas, context) {
  const parentSize = canvasSize(parentCanvas, context);
  const childSize = elementSize(child.element, parentSize.width, context);
  return `#place(dx: ${typstLength(child.x)}, dy: ${typstLength(child.y)})[
${indent(renderElementBox(child.element, context, childSize), 2)}
]`;
}

function renderElementBox(element, context, forcedSize) {
  if (element.type === "pageBreak") return "#pagebreak()";
  if (element.type === "canvas") return renderCanvasBox(element, context, forcedSize);
  return `#box(${boxArgs(element, forcedSize)})[
${indent(renderElementBody(element, context), 2)}
]`;
}

function renderText(element, text) {
  const style = element.style || {};
  return `#set align(${align(style.align)})
#text(${textArgs(style)})[
${indent(markup(text), 2)}
]`;
}

function renderImage(element, context) {
  const assetPath = typstAssetPath(element.data?.path || "assets/church/logo.png", context.assetPrefix);
  const fit = element.data?.fit === "cover" ? "cover" : "contain";
  return `#image("${typstString(assetPath)}", width: 100%, height: 100%, fit: "${fit}")`;
}

function renderGrid(element, context) {
  const columns = Math.max(1, Number(element.data?.columns || 2));
  const total = Math.max((Number(element.data?.rows || 2) || 2) * columns, element.children?.length || 0);
  const rows = Math.max(1, Number(element.data?.rows || 2), Math.ceil(total / columns));
  const columnSpec = Array(columns).fill("1fr").join(", ");
  const children = [];
  for (let index = 0; index < total; index++) {
    const child = element.children?.[index];
    children.push(child ? `[
${indent(renderElementBox(child, context), 4)}
  ]` : `[]`);
  }
  return `#grid(
  columns: (${columnSpec}),
  rows: ${rows},
  gutter: ${typstLength(element.data?.cellPadding || 6)},
  ${children.join(",\n  ")},
)`;
}

function renderStack(element, context) {
  const dir = element.data?.direction === "horizontal" ? "horizontal" : "vertical";
  const gap = typstLength(element.data?.gap || 8);
  const children = (element.children || []).map((child) => `[
${indent(renderElementBox(child, context), 4)}
  ]`).join(",\n  ");
  if (dir === "horizontal") {
    return `#grid(columns: (${(element.children || []).map(() => "1fr").join(", ") || "1fr"}), gutter: ${gap}, ${children})`;
  }
  return `#stack(dir: ttb, spacing: ${gap},
  ${children}
)`;
}

function renderMusic(element) {
  return `#align(center + horizon)[
  #text(size: 14pt, weight: "bold")[${markup(element.data?.title || "Music / Lead Sheet")}]
  #linebreak()
  #text(size: 9pt, style: "italic")[${markup(element.data?.notes || "Import support TBD")}]
]`;
}

function renderDateText(element) {
  const data = element.data || {};
  return `${data.prefix || ""}${formatDate(data.value, data.format, data.locale)}${data.suffix || ""}`;
}

function formatDate(value, format = "MMMM d, yyyy", locale = "en-US") {
  const date = value ? new Date(`${value}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return String(value || "");
  if (format === "MM/dd/yyyy") return new Intl.DateTimeFormat(locale, { month: "2-digit", day: "2-digit", year: "numeric" }).format(date);
  if (format === "EEEE, MMMM d, yyyy") return new Intl.DateTimeFormat(locale, { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(date);
  if (format === "MMM d, yyyy") return new Intl.DateTimeFormat(locale, { month: "short", day: "numeric", year: "numeric" }).format(date);
  return new Intl.DateTimeFormat(locale, { month: "long", day: "numeric", year: "numeric" }).format(date);
}

function boxArgs(element, forcedSize) {
  const style = element.style || {};
  const args = [
    `width: ${typstLength(forcedSize?.width ?? element.width, { allowAuto: true })}`,
    `height: ${typstLength(forcedSize?.height ?? element.height, { allowAuto: true })}`,
    `inset: ${typstLength(element.padding)}`,
  ];
  if (style.background && style.background !== "transparent") args.push(`fill: ${color(style.background)}`);
  if (numericLength(style.borderWidth) > 0) args.push(`stroke: ${typstLength(style.borderWidth)} + ${color(style.borderColor || "#d8cdbd")}`);
  return args.join(", ");
}

function canvasBoxArgs(element, context, forcedSize) {
  const size = forcedSize || canvasSize(element, context);
  return [`width: ${typstLength(size.width)}`, `height: ${typstLength(size.height)}`, "inset: 0pt"].join(", ");
}

function canvasSize(element, context) {
  const pageWidth = numericLength(context.page?.width || 672);
  const pageHeight = numericLength(context.page?.height || 816);
  const requestedWidth = pixelLength(element.width, pageWidth, pageWidth);
  const content = canvasContentExtent(element, requestedWidth, context);
  const width = Math.max(requestedWidth, content.width);
  const requestedHeight = String(element.height ?? "auto").trim() === "auto" ? 0 : pixelLength(element.height, pageHeight, 0);
  const height = Math.min(pageHeight, Math.max(requestedHeight, content.height, 72));
  return { width, height };
}

function canvasContentExtent(element, baseWidth, context) {
  return (element.children || []).reduce((extent, child) => {
    const size = elementSize(child.element, baseWidth, context);
    return {
      width: Math.max(extent.width, numericLength(child.x) + size.width),
      height: Math.max(extent.height, numericLength(child.y) + size.height),
    };
  }, { width: 0, height: 0 });
}

function elementSize(element, baseWidth, context) {
  if (element.type === "canvas") return canvasSize(element, context);
  return {
    width: Math.max(1, pixelLength(element.width, baseWidth, 120)),
    height: Math.max(1, pixelLength(element.height, numericLength(context.page?.height || 816), 80)),
  };
}

function textArgs(style) {
  const args = [
    `font: "${typstString(style.font || "Calibri")}"`,
    `size: ${typstLength(style.fontSize || 11)}`,
    `fill: ${color(style.color || "#251d18")}`,
  ];
  if (style.fontWeight && style.fontWeight !== "regular") args.push(`weight: "${typstString(style.fontWeight)}"`);
  if (style.fontStyle && style.fontStyle !== "normal") args.push(`style: "${typstString(style.fontStyle)}"`);
  return args.join(", ");
}

function typstAssetPath(assetPath, assetPrefix) {
  return `${assetPrefix}/${normalizeAssetPath(assetPath).replace(/^assets\//, "")}`;
}

function color(value) {
  if (!/^#[0-9A-Fa-f]{6}$/.test(String(value))) return `rgb("#ffffff")`;
  return `rgb("${value}")`;
}

function align(value) {
  if (value === "center") return "center";
  if (value === "right") return "right";
  return "left";
}

function px(value) {
  const number = Number(value);
  return Number.isFinite(number) ? round(number * ptPerPx) : 0;
}

function typstLength(value, { allowAuto = false } = {}) {
  if (typeof value === "number") return `${px(value)}pt`;
  const text = String(value ?? "0").trim();
  if (allowAuto && text === "auto") return "auto";
  if (/^-?[0-9]+(\.[0-9]+)?(pt|in|cm|mm|em|%|fr)$/.test(text)) return text;
  const number = Number(text);
  return Number.isFinite(number) ? `${px(number)}pt` : "0pt";
}

function numericLength(value) {
  if (typeof value === "number") return value;
  const number = Number.parseFloat(String(value ?? "0"));
  return Number.isFinite(number) ? number : 0;
}

function pixelLength(value, base, fallback = 0) {
  if (typeof value === "number") return value;
  const text = String(value ?? "").trim();
  if (!text || text === "auto") return fallback;
  if (text.endsWith("%")) return (Number.parseFloat(text) / 100) * base;
  if (text.endsWith("fr")) return fallback;
  const number = Number.parseFloat(text);
  return Number.isFinite(number) ? number : fallback;
}

function round(value) {
  return Math.round(value * 1000) / 1000;
}

function typstString(value = "") {
  return String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function markup(value = "") {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("#", "\\#")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("$", "\\$")
    .replaceAll("*", "\\*")
    .replaceAll("_", "\\_")
    .replaceAll("`", "\\`");
}

function indent(text, spaces) {
  const prefix = " ".repeat(spaces);
  return String(text).split("\n").map((line) => `${prefix}${line}`).join("\n");
}
