import { normalizeAssetPath } from "./storage.js";

const ptPerPx = 0.75;

export function renderTypst(project) {
  const page = project.page || {};
  const elements = Array.isArray(project.elements) ? project.elements : [];
  return `// Generated by Church Bulletin Builder. Edit document.json in the app.
#set page(width: ${page.typstWidth || "7in"}, height: ${page.typstHeight || "8.5in"}, margin: 0pt, fill: ${color(page.background || "#ffffff")})
#set text(font: "Calibri", size: 11pt)
#set par(first-line-indent: 0pt, spacing: 0.35em)

${elements.map(renderElement).join("\n\n")}
`;
}

function renderElement(element) {
  const body = renderElementBody(element);
  return `#place(dx: ${typstLength(element.x)}, dy: ${typstLength(element.y)})[
  #box(${boxArgs(element)})[
${indent(body, 4)}
  ]
]`;
}

function renderElementBody(element) {
  if (element.type === "image") return renderImage(element);
  if (element.type === "grid") return renderGrid(element);
  if (element.type === "stack") return renderStack(element);
  if (element.type === "music") return renderMusic(element);
  if (element.type === "date") return renderText(element, renderDateText(element));
  return renderText(element, element.data?.text || "");
}

function renderText(element, text) {
  const style = element.style || {};
  return `#set align(${align(style.align)})
#text(${textArgs(style)})[
${indent(markup(text), 2)}
]`;
}

function renderImage(element) {
  const assetPath = typstAssetPath(element.data?.path || "assets/church/logo.png");
  const fit = element.data?.fit === "cover" ? "cover" : "contain";
  return `#image("${typstString(assetPath)}", width: 100%, height: 100%, fit: "${fit}")`;
}

function renderGrid(element) {
  const rows = Math.max(1, Number(element.data?.rows || 2));
  const columns = Math.max(1, Number(element.data?.columns || 2));
  const cells = Array.isArray(element.data?.cells) ? element.data.cells : [];
  const columnSpec = Array(columns).fill("1fr").join(", ");
  const children = [];
  for (let index = 0; index < rows * columns; index++) {
    children.push(`[#text(${textArgs(element.style || {})})[${markup(cells[index] || "")}]]`);
  }
  return `#grid(
  columns: (${columnSpec}),
  rows: ${rows},
  gutter: ${typstLength(element.data?.cellPadding || 6)},
  ${children.join(",\n  ")},
)`;
}

function renderStack(element) {
  const items = Array.isArray(element.data?.items) ? element.data.items : [];
  const dir = element.data?.direction === "horizontal" ? "horizontal" : "vertical";
  const gap = typstLength(element.data?.gap || 8);
  const children = items.map((item) => `[#text(${textArgs(element.style || {})})[${markup(item)}]]`).join(",\n  ");
  if (dir === "horizontal") {
    return `#grid(columns: (${items.map(() => "1fr").join(", ") || "1fr"}), gutter: ${gap}, ${children})`;
  }
  return `#stack(dir: ttb, spacing: ${gap},
  ${children}
)`;
}

function renderMusic(element) {
  return `#align(center + horizon)[
  #text(size: 14pt, weight: "bold")[${markup(element.data?.title || "Music / Lead Sheet")}]
  #linebreak()
  #text(size: 9pt, style: "italic")[${markup(element.data?.notes || "Import support TBD")}]
]`;
}

function renderDateText(element) {
  const data = element.data || {};
  return `${data.prefix || ""}${formatDate(data.value, data.format, data.locale)}${data.suffix || ""}`;
}

function formatDate(value, format = "MMMM d, yyyy", locale = "en-US") {
  const date = value ? new Date(`${value}T00:00:00`) : new Date();
  if (Number.isNaN(date.getTime())) return String(value || "");
  if (format === "MM/dd/yyyy") return new Intl.DateTimeFormat(locale, { month: "2-digit", day: "2-digit", year: "numeric" }).format(date);
  if (format === "EEEE, MMMM d, yyyy") return new Intl.DateTimeFormat(locale, { weekday: "long", month: "long", day: "numeric", year: "numeric" }).format(date);
  if (format === "MMM d, yyyy") return new Intl.DateTimeFormat(locale, { month: "short", day: "numeric", year: "numeric" }).format(date);
  return new Intl.DateTimeFormat(locale, { month: "long", day: "numeric", year: "numeric" }).format(date);
}

function boxArgs(element) {
  const style = element.style || {};
  const args = [
    `width: ${typstLength(element.width, { allowAuto: true })}`,
    `height: ${typstLength(element.height, { allowAuto: true })}`,
    `inset: ${typstLength(element.padding)}`,
  ];
  if (style.background && style.background !== "transparent") args.push(`fill: ${color(style.background)}`);
  if (numericLength(style.borderWidth) > 0) args.push(`stroke: ${typstLength(style.borderWidth)} + ${color(style.borderColor || "#d8cdbd")}`);
  return args.join(", ");
}

function textArgs(style) {
  const args = [
    `font: "${typstString(style.font || "Calibri")}"`,
    `size: ${typstLength(style.fontSize || 11)}`,
    `fill: ${color(style.color || "#251d18")}`,
  ];
  if (style.fontWeight && style.fontWeight !== "regular") args.push(`weight: "${typstString(style.fontWeight)}"`);
  if (style.fontStyle && style.fontStyle !== "normal") args.push(`style: "${typstString(style.fontStyle)}"`);
  return args.join(", ");
}

function typstAssetPath(assetPath) {
  return `../../../${normalizeAssetPath(assetPath)}`;
}

function color(value) {
  if (!/^#[0-9A-Fa-f]{6}$/.test(String(value))) return `rgb("#ffffff")`;
  return `rgb("${value}")`;
}

function align(value) {
  if (value === "center") return "center";
  if (value === "right") return "right";
  return "left";
}

function px(value) {
  const number = Number(value);
  return Number.isFinite(number) ? round(number * ptPerPx) : 0;
}

function typstLength(value, { allowAuto = false } = {}) {
  if (typeof value === "number") return `${px(value)}pt`;
  const text = String(value ?? "0").trim();
  if (allowAuto && text === "auto") return "auto";
  if (/^-?[0-9]+(\.[0-9]+)?(pt|in|cm|mm|em|%|fr)$/.test(text)) return text;
  const number = Number(text);
  return Number.isFinite(number) ? `${px(number)}pt` : "0pt";
}

function numericLength(value) {
  if (typeof value === "number") return value;
  const number = Number.parseFloat(String(value ?? "0"));
  return Number.isFinite(number) ? number : 0;
}

function round(value) {
  return Math.round(value * 1000) / 1000;
}

function typstString(value = "") {
  return String(value).replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function markup(value = "") {
  return String(value)
    .replaceAll("\\", "\\\\")
    .replaceAll("#", "\\#")
    .replaceAll("[", "\\[")
    .replaceAll("]", "\\]")
    .replaceAll("$", "\\$")
    .replaceAll("*", "\\*")
    .replaceAll("_", "\\_")
    .replaceAll("`", "\\`");
}

function indent(text, spaces) {
  const prefix = " ".repeat(spaces);
  return String(text).split("\n").map((line) => `${prefix}${line}`).join("\n");
}
