/**
 * @cbb/core/ids — identity types and helpers for the Church Bulletin Builder.
 *
 * Exports:
 *   - All branded id types (compile-time nominal typing)
 *   - IdPort interface + makeSequentialIdPort (test helper)
 *   - UUID validation utilities
 *   - Constructor / validator / mint / format / extract functions per id class
 */

export type {
  AiExchangeId,
  BackupHandoffId,
  BundleEntryId,
  BundleId,
  ChurchProfileScheduleId,
  ContentRuleId,
  CustomElementTypeId,
  DocumentElementId,
  FieldContractId,
  HistorySnapshotId,
  LocalResourceId,
  PackDraftId,
  PortableAssetId,
  PortableAssetRef,
  PortableFontId,
  PortableFontRef,
  PortableSongWorkId,
  PortableSongWorkRef,
  RepeatItemId,
  ResourcePackContentId,
  ResourcePackId,
  RightsCreditId,
  RightsCreditRef,
  ScriptureProviderConnectionId,
  ScriptureTranslationId,
  ScriptureTranslationRef,
  SharedLibraryConnectionId,
  WeeklyChecklistItemId,
  WorkspaceId,
} from "./types.js";

export type { IdPort } from "./port.js";
export { makeSequentialIdPort } from "./port.js";

export { isCanonicalUuid, normaliseUuid } from "./uuid.js";

export {
  extractAssetId,
  extractCreditId,
  extractFontId,
  extractSongWorkId,
  extractTranslationId,
  formatAssetRef,
  formatCreditRef,
  formatFontRef,
  formatSongWorkRef,
  formatTranslationRef,
  isAiExchangeId,
  isBackupHandoffId,
  isBundleEntryId,
  isBundleId,
  isChurchProfileScheduleId,
  isContentRuleId,
  isCustomElementTypeId,
  isDocumentElementId,
  isFieldContractId,
  isHistorySnapshotId,
  isLocalResourceId,
  isPackDraftId,
  isPortableAssetId,
  isPortableAssetRef,
  isPortableFontId,
  isPortableFontRef,
  isPortableSongWorkId,
  isPortableSongWorkRef,
  isRepeatItemId,
  isResourcePackContentId,
  isResourcePackId,
  isRightsCreditId,
  isRightsCreditRef,
  isScriptureProviderConnectionId,
  isScriptureTranslationId,
  isScriptureTranslationRef,
  isSharedLibraryConnectionId,
  isWeeklyChecklistItemId,
  isWorkspaceId,
  mintAiExchangeId,
  mintBackupHandoffId,
  mintBundleEntryId,
  mintBundleId,
  mintChurchProfileScheduleId,
  mintContentRuleId,
  mintCustomElementTypeId,
  mintDocumentElementId,
  mintFieldContractId,
  mintHistorySnapshotId,
  mintLocalResourceId,
  mintPackDraftId,
  mintPortableAssetId,
  mintPortableAssetRef,
  mintPortableFontId,
  mintPortableFontRef,
  mintPortableSongWorkId,
  mintPortableSongWorkRef,
  mintRightsCreditId,
  mintRightsCreditRef,
  mintScriptureProviderConnectionId,
  mintScriptureTranslationId,
  mintScriptureTranslationRef,
  mintSharedLibraryConnectionId,
  mintWeeklyChecklistItemId,
  mintWorkspaceId,
  parseAiExchangeId,
  parseBackupHandoffId,
  parseBundleEntryId,
  parseBundleId,
  parseChurchProfileScheduleId,
  parseContentRuleId,
  parseCustomElementTypeId,
  parseDocumentElementId,
  parseFieldContractId,
  parseHistorySnapshotId,
  parseLocalResourceId,
  parsePackDraftId,
  parsePortableAssetId,
  parsePortableAssetRef,
  parsePortableFontId,
  parsePortableFontRef,
  parsePortableSongWorkId,
  parsePortableSongWorkRef,
  parseRepeatItemId,
  parseResourcePackContentId,
  parseResourcePackId,
  parseRightsCreditId,
  parseRightsCreditRef,
  parseScriptureProviderConnectionId,
  parseScriptureTranslationId,
  parseScriptureTranslationRef,
  parseSharedLibraryConnectionId,
  parseWeeklyChecklistItemId,
  parseWorkspaceId,
} from "./constructors.js";
