import { useState, type ReactNode } from 'react';
import { BlockFormattingModal } from './BlockFormattingModal';
import { childBlocks, findBlock, flattenBlocks, updateBlockTree } from '../shared/blocks';
import type { BulletinBlock, BulletinDocumentV1, LibraryManifestV1, Paragraph, TemplateV1 } from '../shared/types';

const paragraphs = (text: string): Paragraph[] => text.split(/\n\s*\n/).map(value => ({ type: 'paragraph', children: [{ type: 'text', text: value.replace(/\n/g, ' ') }] }));
const paragraphText = (content: Paragraph[]) => content.map(p => p.children.map(c => c.type === 'text' ? c.text : '✠').join('')).join('\n\n');
export function WeeklyEditor({ document, template, library, root, relativePath, onChange, onError }: { document: BulletinDocumentV1; template: TemplateV1; library?: LibraryManifestV1; root?: string; relativePath: string; onChange(document: BulletinDocumentV1): void; onError(message: string): void }) {
  const [formattingBlockId, setFormattingBlockId] = useState<string>();
  const [formatPickerOpen, setFormatPickerOpen] = useState(false);
  const [lookupStatus, setLookupStatus] = useState<Record<string, { state: 'loading' | 'success' | 'error'; text: string }>>({});
  const songs = [...new Map(library?.items.filter(item => item.kind === 'song').sort((a, b) => a.version - b.version).map(item => [item.id, item])).values()];
  const missingLibraryReference = (block: BulletinBlock) => (block.type === 'song' || block.type === 'libraryText') && Boolean(library) && !library!.items.some(item => item.id === block.libraryItemId && (!block.libraryItemVersion || item.version === block.libraryItemVersion));
  const hasEditableText = (block: BulletinBlock) => block.type !== 'spacer' && block.type !== 'fullPageAsset';
  const hasWeeklyCustomBindings = (block: BulletinBlock) => block.type === 'custom' && block.bindings.some(binding => binding.source === 'weekly');
  const updateInfo = (key: keyof BulletinDocumentV1['info'], value: string) => onChange({ ...document, info: { ...document.info, [key]: value } });
  const updateChurchName = (name: string) => onChange({ ...document, church: { ...document.church, name } });
  const updatePageMargin = (marginIn: number) => onChange({ ...document, layout: { ...document.layout, marginIn: Math.max(0, Math.min(1.25, marginIn)) } });
  const resetPageMargin = () => { const layout = { ...document.layout }; delete layout.marginIn; onChange({ ...document, layout: Object.keys(layout).length ? layout : undefined }); };
  const updateBlock = (id: string, next: BulletinBlock) => onChange({ ...document, blocks: updateBlockTree(document.blocks, id, next) });
  const paragraphHeader = (block: BulletinBlock) => { const header = block.type === 'paragraph' ? childBlocks(block)?.find(child => child.type === 'richText' && child.role === 'header') : undefined; return header?.type === 'richText' ? paragraphText(header.content) : ''; };
  const blockName = (block: BulletinBlock) => block.type === 'custom' ? block.name : block.type === 'paragraph' ? paragraphHeader(block) || 'Paragraph' : block.type === 'richText' && block.role ? (block.role === 'header' ? 'Header text' : 'Paragraph text') : block.label ?? ('text' in block ? block.text : block.type === 'announcements' ? 'Announcements' : block.type === 'titlePage' ? 'Cover' : block.type);
  const updateChildren = (parent: BulletinBlock, children: BulletinBlock[]) => {
    if (parent.type === 'churchInfo' || parent.type === 'group') updateBlock(parent.id, { ...parent, children });
    if (parent.type === 'paragraph') updateBlock(parent.id, { ...parent, children: children.filter(child => child.type === 'richText') });
  };
  const nestedEditors = (parent: BulletinBlock): ReactNode => {
    const children = childBlocks(parent) ?? [];
    const isParagraph = parent.type === 'paragraph';
    return <div className="nested-blocks"><div className="nested-blocks-heading"><b>{isParagraph ? 'Text blocks' : 'Paragraphs'}</b><span>{isParagraph ? 'Header and body formatting are completely independent.' : 'Each paragraph keeps its header and body together.'}</span></div>{children.map((child, childIndex) => <details className="nested-block-editor collapsible-editor" key={child.id}><summary><div><span className="block-type">{child.type}{child.presentation ? ' · formatted' : ''}</span><b>{blockName(child)}</b></div><div className="reorder" onClick={event => event.preventDefault()}><button className="format-block-button" onClick={() => setFormattingBlockId(child.id)}>Format</button>{!isParagraph && <><button title="Move up" onClick={() => { const next = [...children]; if (childIndex > 0) [next[childIndex - 1], next[childIndex]] = [next[childIndex], next[childIndex - 1]]; updateChildren(parent, next); }}>↑</button><button title="Move down" onClick={() => { const next = [...children]; if (childIndex < next.length - 1) [next[childIndex + 1], next[childIndex]] = [next[childIndex], next[childIndex + 1]]; updateChildren(parent, next); }}>↓</button></>}{(!isParagraph || child.role === 'header') && <button className="danger-text" title="Remove element" onClick={() => updateChildren(parent, children.filter(item => item.id !== child.id))}>×</button>}</div></summary><div className="collapsible-editor-fields">{(child.type === 'heading' || child.type === 'sectionHeading' || child.type === 'sermonTitle') && <label>Heading<input value={child.text} onChange={event => updateBlock(child.id, { ...child, text: event.target.value })} /></label>}{child.type === 'richText' && <label>{child.role === 'header' ? 'Header text' : child.role === 'body' ? 'Paragraph text' : 'Text'}<textarea rows={child.role === 'header' ? 2 : 4} value={paragraphText(child.content)} onChange={event => updateBlock(child.id, { ...child, content: paragraphs(event.target.value) })} /></label>}{childBlocks(child) && nestedEditors(child)}</div></details>)}<div className="nested-add-actions">{isParagraph ? !children.some(child => child.type === 'richText' && child.role === 'header') && <button className="secondary" onClick={() => updateChildren(parent, [{ id: `${parent.id}-header`, type: 'richText', role: 'header', content: paragraphs('New heading'), presentation: { fontWeight: 'bold', marginIn: { top: 0, bottom: 0 }, paddingIn: { top: 0, right: 0, bottom: 0, left: 0 } } }, ...children])}>＋ Header</button> : <button className="secondary" onClick={() => updateChildren(parent, [...children, { id: `paragraph-${Date.now()}`, type: 'paragraph', children: [{ id: `paragraph-body-${Date.now()}`, type: 'richText', role: 'body', content: paragraphs('New text'), presentation: { marginIn: { top: 0, bottom: 0 }, paddingIn: { top: 0, right: 0, bottom: 0, left: 0 } } }] }])}>＋ Paragraph</button>}</div></div>;
  };
  const move = (index: number, by: number) => {
    const next = [...document.blocks]; const target = index + by;
    if (target < 0 || target >= next.length) return;
    [next[index], next[target]] = [next[target], next[index]]; onChange({ ...document, blocks: next });
  };
  const addPage = async () => {
    if (!root || !window.bulletin) return;
    try {
      const asset = await window.bulletin.importAsset(root, `${relativePath.replace(/[/\\]bulletin\.json$/, '')}/assets`);
      if (!asset) return;
      onChange({ ...document, blocks: [...document.blocks, { id: `page-${Date.now()}`, type: 'fullPageAsset', asset, weeklyEditable: true }] });
    } catch (error) { onError(error instanceof Error ? error.message : String(error)); }
  };
  const chooseBlockAsset = async (block: Extract<BulletinBlock, { type: 'titlePage' | 'song' }>) => {
    if (!root || !window.bulletin) return;
    try {
      const asset = await window.bulletin.importAsset(root, `${relativePath.replace(/[/\\]bulletin\.json$/, '')}/assets`);
      if (asset) updateBlock(block.id, { ...block, asset });
    } catch (error) { onError(error instanceof Error ? error.message : String(error)); }
  };
  const lookup = async (block: Extract<BulletinBlock, { type: 'scriptureReading' }>) => {
    if (!window.bulletin) {
      setLookupStatus(current => ({ ...current, [block.id]: { state: 'error', text: 'Passage import is unavailable. Open the passage and paste the approved text manually.' } }));
      return;
    }
    setLookupStatus(current => ({ ...current, [block.id]: { state: 'loading', text: 'Loading the public Bible Gateway passage…' } }));
    try {
      const resolved = await window.bulletin.lookupScripture({ reference: block.reference, translation: block.translation });
      updateBlock(block.id, { ...block, resolved });
      setLookupStatus(current => ({ ...current, [block.id]: { state: 'success', text: `Added ${block.reference} (${block.translation.toUpperCase()}).` } }));
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      setLookupStatus(current => ({ ...current, [block.id]: { state: 'error', text: message } }));
      onError(message);
    }
  };
  const openScripture = async (block: Extract<BulletinBlock, { type: 'scriptureReading' }>) => {
    try {
      if (window.bulletin) await window.bulletin.openScripture(block.reference, block.translation);
      else window.open(`https://www.biblegateway.com/passage/?search=${encodeURIComponent(block.reference)}&version=${encodeURIComponent(block.translation)}`, '_blank', 'noopener,noreferrer');
    } catch (error) { onError(error instanceof Error ? error.message : String(error)); }
  };
  return <div className="editor-scroll">
    <section className="editor-card essentials"><div className="eyebrow">This Sunday</div><label>Service date<input type="date" value={document.info.date} onChange={e => updateInfo('date', e.target.value)} /></label><label>Church week<input value={document.info.churchWeek} onChange={e => updateInfo('churchWeek', e.target.value)} /></label><label>Series<input value={document.info.series ?? ''} onChange={e => updateInfo('series', e.target.value)} /></label><label>Sermon title<input value={document.info.title} onChange={e => updateInfo('title', e.target.value)} /></label><label>Church name<input value={document.church.name} onChange={e => updateChurchName(e.target.value)} /></label><div className="page-margin-control"><label>Page margin (inches)<input type="number" min="0" max="1.25" step="0.05" value={document.layout?.marginIn ?? template.theme.marginIn} onChange={event => { if (Number.isFinite(event.currentTarget.valueAsNumber)) updatePageMargin(event.currentTarget.valueAsNumber); }} /><small className="field-help">Applies to this bulletin only. Template default: {template.theme.marginIn} in.</small></label><button type="button" className="text-button" disabled={document.layout?.marginIn === undefined} onClick={resetPageMargin}>Use template margin</button></div></section>
    <div className="scripture-source-note"><b>Bible Gateway passage import</b><span>No login required. The displayed publisher notice is saved with the passage; verify that your bulletin stays within the translation’s quotation terms.</span></div>
    <div className="editor-section-title"><div><div className="eyebrow">Order of worship</div><h2>Weekly content</h2></div><div className="weekly-content-actions"><button className="secondary" onClick={() => setFormatPickerOpen(true)}>Fine-tune layout</button><button className="secondary" onClick={addPage}>＋ One-off page</button></div></div>
    {document.blocks.map((block, index) => (hasEditableText(block) || block.weeklyEditable || missingLibraryReference(block)) && <details className="editor-card block-editor collapsible-editor" key={block.id}>
      <summary><div><span className="block-type">{block.type}{block.presentation ? ' · formatted' : ''}</span><h3>{blockName(block)}</h3></div><div className="reorder" onClick={event => event.preventDefault()}><button className="format-block-button" title="Format block" onClick={() => setFormattingBlockId(block.id)}>Format</button><button title="Move up" onClick={() => move(index, -1)}>↑</button><button title="Move down" onClick={() => move(index, 1)}>↓</button></div></summary><div className="collapsible-editor-fields">
      {missingLibraryReference(block) && !block.weeklyEditable && <div className="missing-template-content"><b>Template content needs attention</b><span>This block is normally hidden during weekly editing, but its library item is missing. Choose a replacement below or remove it from this bulletin.</span></div>}
      {(block.type === 'sermonTitle' || block.type === 'heading' || block.type === 'sectionHeading') && <label>Text<input value={block.text} onChange={e => updateBlock(block.id, { ...block, text: e.target.value })} /></label>}
      {block.type === 'richText' && <label>Text<textarea rows={6} value={paragraphText(block.content)} onChange={event => updateBlock(block.id, { ...block, content: paragraphs(event.target.value) })} /></label>}
      {block.type === 'paragraph' && nestedEditors(block)}
      {block.type === 'responsiveReading' && <>{block.entries.map((entry, entryIndex) => <div className="response-editor" key={entryIndex}><label>Speaker<input value={entry.reader} onChange={event => updateBlock(block.id, { ...block, entries: block.entries.map((item, index) => index === entryIndex ? { ...item, reader: event.target.value } : item) })} /></label><label>Response<textarea rows={4} value={paragraphText(entry.content)} onChange={event => updateBlock(block.id, { ...block, entries: block.entries.map((item, index) => index === entryIndex ? { ...item, content: paragraphs(event.target.value) } : item) })} /></label><button className="danger-text" onClick={() => updateBlock(block.id, { ...block, entries: block.entries.filter((_item, index) => index !== entryIndex) })}>Remove response</button></div>)}<button className="secondary" onClick={() => updateBlock(block.id, { ...block, entries: [...block.entries, { reader: 'M', content: paragraphs('New response') }] })}>＋ Response</button></>}
      {block.type === 'scriptureReading' && <><div className="field-row"><label>Reference<input value={block.reference} placeholder="Matthew 9:9-13" onChange={e => updateBlock(block.id, { ...block, reference: e.target.value, resolved: undefined })} /></label><label>Translation code<input value={block.translation} placeholder="NIV" onChange={e => updateBlock(block.id, { ...block, translation: e.target.value, resolved: undefined })} /></label></div><label>Introduction<textarea rows={2} value={block.caption ?? ''} onChange={e => updateBlock(block.id, { ...block, caption: e.target.value })} /></label><div className="scripture-actions"><button className="secondary scripture-fetch" disabled={lookupStatus[block.id]?.state === 'loading' || !block.reference.trim()} onClick={() => lookup(block)}>{lookupStatus[block.id]?.state === 'loading' ? 'Importing…' : 'Import passage'}</button><button className="text-button" onClick={() => openScripture(block)}>Open on Bible Gateway ↗</button></div>{lookupStatus[block.id] && <p className={`lookup-status ${lookupStatus[block.id].state}`} role="status" aria-live="polite">{lookupStatus[block.id].text}</p>}<details><summary>Passage text or manual fallback</summary><textarea rows={8} value={block.resolved ? paragraphText(block.resolved.content) : ''} placeholder="Paste the approved passage text here…" onChange={e => updateBlock(block.id, { ...block, resolved: { content: paragraphs(e.target.value), source: 'manual', retrievedAt: new Date().toISOString(), attribution: `${block.translation.toUpperCase()} — text supplied by user` } })} /></details></>}
      {block.type === 'song' && (() => { const selected = library?.items.filter(item => item.id === block.libraryItemId && (!block.libraryItemVersion || item.version === block.libraryItemVersion)).sort((a, b) => b.version - a.version)[0]; return <><label>Library song<select value={block.libraryItemId} onChange={e => { const item = songs.find(song => song.id === e.target.value); updateBlock(block.id, { ...block, libraryItemId: e.target.value, libraryItemVersion: item?.version, contentOverride: undefined }); }}><option value="">Choose a song…</option>{songs.map(item => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><div className="field-row"><label>Display title<input value={block.title ?? ''} onChange={e => updateBlock(block.id, { ...block, title: e.target.value })} /></label><label>Presentation<select value={block.renderMode} onChange={e => updateBlock(block.id, { ...block, renderMode: e.target.value as 'lyrics' | 'asset' })}><option value="lyrics">Lyrics</option><option value="asset">Music image</option></select></label></div>{block.renderMode === 'lyrics' && <details><summary>Edit lyrics for this bulletin</summary><textarea rows={10} value={paragraphText(block.contentOverride ?? selected?.content ?? [])} placeholder="Enter song lyrics…" onChange={event => updateBlock(block.id, { ...block, contentOverride: paragraphs(event.target.value) })} />{block.contentOverride && <button className="danger-text content-reset" onClick={() => updateBlock(block.id, { ...block, contentOverride: undefined })}>Restore library lyrics</button>}</details>}{block.renderMode === 'asset' && <button className="secondary" onClick={() => chooseBlockAsset(block)}>{block.asset ? `Replace ${block.asset.alt ?? 'asset'}` : 'Choose music image or PDF'}</button>}</>; })()}
      {block.type === 'libraryText' && (() => { const selected = library?.items.filter(item => item.id === block.libraryItemId && (!block.libraryItemVersion || item.version === block.libraryItemVersion)).sort((a, b) => b.version - a.version)[0]; return <><label>Library text<select value={block.libraryItemId} onChange={e => { const item = library?.items.filter(item => item.kind === 'liturgy').sort((a, b) => b.version - a.version).find(item => item.id === e.target.value); updateBlock(block.id, { ...block, libraryItemId: e.target.value, libraryItemVersion: item?.version, contentOverride: undefined }); }}><option value="">Choose reusable text…</option>{missingLibraryReference(block) && <option value={block.libraryItemId}>Missing: {block.title ?? block.libraryItemId}</option>}{[...new Map(library?.items.filter(item => item.kind === 'liturgy').sort((a, b) => a.version - b.version).map(item => [item.id, item])).values()].map(item => <option value={item.id} key={item.id}>{item.title}</option>)}</select></label><details><summary>Edit reusable text for this bulletin</summary><textarea rows={8} value={paragraphText(block.contentOverride ?? selected?.content ?? [])} onChange={event => updateBlock(block.id, { ...block, contentOverride: paragraphs(event.target.value) })} />{block.contentOverride && <button className="danger-text content-reset" onClick={() => updateBlock(block.id, { ...block, contentOverride: undefined })}>Restore library text</button>}</details></>; })()}
      {block.type === 'announcements' && <>{block.items.map((item, itemIndex) => <div className="announcement-editor" key={item.id}><label>Title<input value={item.title} onChange={e => updateBlock(block.id, { ...block, items: block.items.map((old, i) => i === itemIndex ? { ...old, title: e.target.value } : old) })} /></label><label>Details<textarea rows={4} value={paragraphText(item.content)} onChange={e => updateBlock(block.id, { ...block, items: block.items.map((old, i) => i === itemIndex ? { ...old, content: paragraphs(e.target.value) } : old) })} /></label></div>)}<button className="secondary" onClick={() => updateBlock(block.id, { ...block, items: [...block.items, { id: `announcement-${Date.now()}`, title: 'New announcement', content: [paragraphs('')[0]] }] })}>＋ Announcement</button></>}
      {block.type === 'custom' && <div className="custom-weekly-fields"><div className="field-row"><label>Block heading<input value={block.name} onChange={event => updateBlock(block.id, { ...block, name: event.target.value, label: event.target.value })} /></label><label>Content layout<textarea rows={3} value={block.layoutText} onChange={event => updateBlock(block.id, { ...block, layoutText: event.target.value })} /></label></div>{block.bindings.filter(binding => binding.source === 'weekly').map(binding => <label key={binding.key}>{binding.label}{binding.multiline
        ? <textarea rows={4} value={block.values?.[binding.key] ?? binding.defaultValue ?? ''} onChange={event => updateBlock(block.id, { ...block, values: { ...block.values, [binding.key]: event.target.value } })} />
        : <input value={block.values?.[binding.key] ?? binding.defaultValue ?? ''} onChange={event => updateBlock(block.id, { ...block, values: { ...block.values, [binding.key]: event.target.value } })} />}</label>)}{!hasWeeklyCustomBindings(block) && <p className="helper">This block is filled automatically from bulletin details.</p>}</div>}
      {block.type === 'titlePage' && <><p className="helper">Use the standard cover or replace it for this week with a complete image/PDF page.</p><button className="secondary" onClick={() => chooseBlockAsset(block)}>{block.asset ? `Replace ${block.asset.alt ?? 'cover'}` : 'Choose custom cover'}</button>{block.asset && <button className="danger-text" onClick={() => { const { asset: _asset, ...standard } = block; updateBlock(block.id, standard); }}>Use standard cover</button>}</>}
      {(block.type === 'churchInfo' || block.type === 'group') && nestedEditors(block)}
      {block.type === 'copyright' && <label>Additional copyright text<textarea rows={5} value={paragraphText(block.extra ?? [])} placeholder="Library and Scripture notices are generated automatically." onChange={event => updateBlock(block.id, { ...block, extra: paragraphs(event.target.value) })} /></label>}
      {block.type === 'fullPageAsset' && <><p className="helper">{block.asset.alt ?? block.asset.path}</p><button className="danger-text" onClick={() => onChange({ ...document, blocks: document.blocks.filter(item => item.id !== block.id) })}>Remove page</button></>}
      {missingLibraryReference(block) && !block.weeklyEditable && <button className="danger-text" onClick={() => onChange({ ...document, blocks: document.blocks.filter(item => item.id !== block.id) })}>Remove from this bulletin</button>}
      </div>
    </details>)}
    {formatPickerOpen && <div className="modal-backdrop block-modal-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) setFormatPickerOpen(false); }}><section className="weekly-block-picker" role="dialog" aria-modal="true" aria-labelledby="weekly-format-title"><header><div><div className="eyebrow">This bulletin only</div><h2 id="weekly-format-title">Choose a block to fine-tune</h2><p>Every block and nested element can have its own weekly layout override.</p></div><button aria-label="Close block picker" onClick={() => setFormatPickerOpen(false)}>×</button></header><div>{flattenBlocks(document.blocks).map((block, index) => <button key={block.id} onClick={() => { setFormattingBlockId(block.id); setFormatPickerOpen(false); }}><span>{index + 1}</span><div><b>{blockName(block)}</b><small>{block.type}{block.presentation ? ' · Formatted' : ''}</small></div><strong>Format</strong></button>)}</div></section></div>}
    {formattingBlockId && (() => { const block = findBlock(document.blocks, formattingBlockId); return block ? <BlockFormattingModal block={block} template={template} scope="weekly" onClose={() => setFormattingBlockId(undefined)} onSave={(presentation, layout) => { updateBlock(block.id, { ...block, presentation, layout }); setFormattingBlockId(undefined); }} /> : null; })()}
  </div>;
}
